plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'kr.co.kwt'
version = '0.0.2'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    implementation 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            def env = project.findProperty('env') ?: 'dev'
            def snapshotUrl = "https://nexus.kwt.co.kr/repository/maven-snapshots/"
            def releaseUrl = "https://nexus.kwt.co.kr/repository/maven-releases/"

            url = env == 'dev' ? uri(snapshotUrl) : uri(releaseUrl)
            version = env == 'dev' ? version + '-SNAPSHOT' : version

            credentials {
                username = "maven-deploy"
                password = "maven-deploy"
            }
        }
    }
}

tasks.withType(GenerateModuleMetadata) {
    suppressedValidationErrors.add('dependencies-without-versions')
}